//
// MatchScoreBreakdown2015.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** See the 2015 FMS API documentation for a description of each value */
public class MatchScoreBreakdown2015: JSONEncodable {
    public enum Coopertition: String { 
        case None = "None"
        case Unknown = "Unknown"
        case Stack = "Stack"
    }
    public var blue: MatchScoreBreakdown2015Alliance?
    public var red: MatchScoreBreakdown2015Alliance?
    public var coopertition: Coopertition?
    public var coopertitionPoints: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["blue"] = self.blue?.encodeToJSON()
        nillableDictionary["red"] = self.red?.encodeToJSON()
        nillableDictionary["coopertition"] = self.coopertition?.rawValue
        nillableDictionary["coopertition_points"] = self.coopertitionPoints?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
