//
// DistrictRankingEventPoints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DistrictRankingEventPoints: Codable {

    /** TBA Event key for this event. */
    public var eventKey: String
    /** &#x60;true&#x60; if this event is a District Championship event. */
    public var districtCmp: Bool
    /** Points awarded for alliance selection. */
    public var alliancePoints: Int
    /** Points awarded for event awards. */
    public var awardPoints: Int
    /** Points awarded for qualification match performance. */
    public var qualPoints: Int
    /** Points awarded for elimination match performance. */
    public var elimPoints: Int
    /** Total points awarded at this event. */
    public var total: Int


    
    public init(eventKey: String, districtCmp: Bool, alliancePoints: Int, awardPoints: Int, qualPoints: Int, elimPoints: Int, total: Int) {
        self.eventKey = eventKey
        self.districtCmp = districtCmp
        self.alliancePoints = alliancePoints
        self.awardPoints = awardPoints
        self.qualPoints = qualPoints
        self.elimPoints = elimPoints
        self.total = total
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(eventKey, forKey: "event_key")
        try container.encode(districtCmp, forKey: "district_cmp")
        try container.encode(alliancePoints, forKey: "alliance_points")
        try container.encode(awardPoints, forKey: "award_points")
        try container.encode(qualPoints, forKey: "qual_points")
        try container.encode(elimPoints, forKey: "elim_points")
        try container.encode(total, forKey: "total")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        eventKey = try container.decode(String.self, forKey: "event_key")
        districtCmp = try container.decode(Bool.self, forKey: "district_cmp")
        alliancePoints = try container.decode(Int.self, forKey: "alliance_points")
        awardPoints = try container.decode(Int.self, forKey: "award_points")
        qualPoints = try container.decode(Int.self, forKey: "qual_points")
        elimPoints = try container.decode(Int.self, forKey: "elim_points")
        total = try container.decode(Int.self, forKey: "total")
    }
}

