//
// EliminationAllianceStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EliminationAllianceStatus: JSONEncodable {
    public var currentLevelRecord: WLTRecord?
    public var level: String?
    public var playoffAverage: Double?
    public var record: WLTRecord?
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["current_level_record"] = self.currentLevelRecord?.encodeToJSON()
        nillableDictionary["level"] = self.level
        nillableDictionary["playoff_average"] = self.playoffAverage
        nillableDictionary["record"] = self.record?.encodeToJSON()
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
