//
// EventDistrictPointsTiebreakers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class EventDistrictPointsTiebreakers: Codable {

    public var highestQualScores: [Int]?
    public var qualWins: Int?


    
    public init(highestQualScores: [Int]?, qualWins: Int?) {
        self.highestQualScores = highestQualScores
        self.qualWins = qualWins
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(highestQualScores, forKey: "highest_qual_scores")
        try container.encodeIfPresent(qualWins, forKey: "qual_wins")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        highestQualScores = try container.decodeIfPresent([Int].self, forKey: "highest_qual_scores")
        qualWins = try container.decodeIfPresent(Int.self, forKey: "qual_wins")
    }
}

