//
// EventRankingExtraStatsInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventRankingExtraStatsInfo: JSONEncodable {
    /** Name of the field used in the &#x60;extra_stats&#x60; array. */
    public var name: String
    /** Integer expressing the number of digits of precision in the number provided in &#x60;sort_orders&#x60;. */
    public var precision: Double

    public init(name: String, precision: Double) {
        self.name = name
        self.precision = precision
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["precision"] = self.precision
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
