//
// MatchAlliance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MatchAlliance: JSONEncodable {
    /** Score for this alliance. Will be null or -1 for an unplayed match. */
    public var score: Int32?
    public var teamKeys: [String]?
    /** TBA team keys (eg &#x60;frc254&#x60;) of any teams playing as a surrogate. */
    public var surrogateTeamKeys: [String]?
    /** TBA team keys (eg &#x60;frc254&#x60;) of any disqualified teams. */
    public var dqTeamKeys: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["score"] = self.score?.encodeToJSON()
        nillableDictionary["team_keys"] = self.teamKeys?.encodeToJSON()
        nillableDictionary["surrogate_team_keys"] = self.surrogateTeamKeys?.encodeToJSON()
        nillableDictionary["dq_team_keys"] = self.dqTeamKeys?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
