//
// MatchScoreBreakdown2017.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** See the 2017 FMS API documentation for a description of each value. */

open class MatchScoreBreakdown2017: Codable {

    public var blue: MatchScoreBreakdown2017Alliance?
    public var red: MatchScoreBreakdown2017Alliance?


    
    public init(blue: MatchScoreBreakdown2017Alliance?, red: MatchScoreBreakdown2017Alliance?) {
        self.blue = blue
        self.red = red
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(blue, forKey: "blue")
        try container.encodeIfPresent(red, forKey: "red")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        blue = try container.decodeIfPresent(MatchScoreBreakdown2017Alliance.self, forKey: "blue")
        red = try container.decodeIfPresent(MatchScoreBreakdown2017Alliance.self, forKey: "red")
    }
}

