//
// MatchSimpleAlliances.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of alliances, the teams on the alliances, and their score. */
public class MatchSimpleAlliances: JSONEncodable {
    public var blue: MatchAlliance?
    public var red: MatchAlliance?

    public init(blue: MatchAlliance?=nil, red: MatchAlliance?=nil) {
        self.blue = blue
        self.red = red
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["blue"] = self.blue?.encodeToJSON()
        nillableDictionary["red"] = self.red?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
