//
// TeamEventStatusAlliance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TeamEventStatusAlliance: Codable {

    /** Alliance name, may be null. */
    public var name: String?
    /** Alliance number. */
    public var number: Int
    public var backup: TeamEventStatusAllianceBackup?
    /** Order the team was picked in the alliance from 0-2, with 0 being alliance captain. */
    public var pick: Int


    
    public init(name: String?, number: Int, backup: TeamEventStatusAllianceBackup?, pick: Int) {
        self.name = name
        self.number = number
        self.backup = backup
        self.pick = pick
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "name")
        try container.encode(number, forKey: "number")
        try container.encodeIfPresent(backup, forKey: "backup")
        try container.encode(pick, forKey: "pick")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decodeIfPresent(String.self, forKey: "name")
        number = try container.decode(Int.self, forKey: "number")
        backup = try container.decodeIfPresent(TeamEventStatusAllianceBackup.self, forKey: "backup")
        pick = try container.decode(Int.self, forKey: "pick")
    }
}

