//
// TeamRobot.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TeamRobot: JSONEncodable {
    /** Year this robot competed in. */
    public var year: Int32?
    /** Name of the robot as provided by the team. */
    public var robotName: String?
    /** Internal TBA identifier for this robot. */
    public var key: String?
    /** TBA team key for this robot. */
    public var teamKey: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["year"] = self.year?.encodeToJSON()
        nillableDictionary["robot_name"] = self.robotName
        nillableDictionary["key"] = self.key
        nillableDictionary["team_key"] = self.teamKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
