//
// TeamEventStatusAllianceBackup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Backup status, may be null. */
open class TeamEventStatusAllianceBackup: JSONEncodable {

    /** TBA key for the team replaced by the backup. */
    public var out: String?
    /** TBA key for the backup team called in. */
    public var _in: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["out"] = self.out
        nillableDictionary["in"] = self._in

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

