//
// TeamEventStatusRank.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TeamEventStatusRank: JSONEncodable {

    /** Number of teams ranked. */
    public var numTeams: Int32?
    public var ranking: TeamEventStatusRankRanking?
    /** Ordered list of names corresponding to the elements of the &#x60;sort_orders&#x60; array. */
    public var sortOrderInfo: [TeamEventStatusRankSortOrderInfo]?
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["num_teams"] = self.numTeams?.encodeToJSON()
        nillableDictionary["ranking"] = self.ranking?.encodeToJSON()
        nillableDictionary["sort_order_info"] = self.sortOrderInfo?.encodeToJSON()
        nillableDictionary["status"] = self.status

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

