//
// EliminationAllianceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class EliminationAllianceStatus: JSONEncodable {
    public var playoffAverage: Double?
    public var level: String?
    public var record: WLTRecord?
    public var currentLevelRecord: WLTRecord?
    public var status: String?

    public init(playoffAverage: Double?=nil, level: String?=nil, record: WLTRecord?=nil, currentLevelRecord: WLTRecord?=nil, status: String?=nil) {
        self.playoffAverage = playoffAverage
        self.level = level
        self.record = record
        self.currentLevelRecord = currentLevelRecord
        self.status = status
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["playoff_average"] = self.playoffAverage
        nillableDictionary["level"] = self.level
        nillableDictionary["record"] = self.record?.encodeToJSON()
        nillableDictionary["current_level_record"] = self.currentLevelRecord?.encodeToJSON()
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
