//
// Match.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class Match: JSONEncodable {
    public enum CompLevel: String { 
        case Qm = "qm"
        case Ef = "ef"
        case Qf = "qf"
        case Sf = "sf"
        case F = "f"
    }
    /** TBA match key with the format &#x60;yyyy[EVENT_CODE]_[COMP_LEVEL]m[MATCH_NUMBER]&#x60;, where &#x60;yyyy&#x60; is the year, and &#x60;EVENT_CODE&#x60; is the event code of the event, &#x60;COMP_LEVEL&#x60; is (qm, ef, qf, sf, f), and &#x60;MATCH_NUMBER&#x60; is the match number in the competition level. A set number may be appended to the competition level if more than one match in required per set. */
    public var key: String
    /** The competition level the match was played at. */
    public var compLevel: CompLevel
    /** The set number in a series of matches where more than one match is required in the match series. */
    public var setNumber: Int32
    /** The match number of the match in the competition level. */
    public var matchNumber: Int32
    public var alliances: MatchSimpleAlliances?
    /** The color (red/blue) of the winning alliance. Will contain an empty string in the event of no winner, or a tie. */
    public var winningAlliance: String?
    /** Event key of the event the match was played at. */
    public var eventKey: String
    /** UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the scheduled match time, as taken from the published schedule. */
    public var time: Int64?
    /** UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of actual match start time. */
    public var actualTime: Int64?
    /** UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the TBA predicted match start time. */
    public var predictedTime: Int64?
    /** UNIX timestamp (seconds since 1-Jan-1970 00:00:00) when the match result was posted. */
    public var postResultTime: Int64?
    /** Score breakdown for auto, teleop, etc. points. Varies from year to year. May be null. */
    public var scoreBreakdown: AnyObject?
    /** Array of video objects associated with this match. */
    public var videos: [MatchVideos]?

    public init(key: String, compLevel: CompLevel, setNumber: Int32, matchNumber: Int32, alliances: MatchSimpleAlliances?=nil, winningAlliance: String?=nil, eventKey: String, time: Int64?=nil, actualTime: Int64?=nil, predictedTime: Int64?=nil, postResultTime: Int64?=nil, scoreBreakdown: AnyObject?=nil, videos: [MatchVideos]?=nil) {
        self.key = key
        self.compLevel = compLevel
        self.setNumber = setNumber
        self.matchNumber = matchNumber
        self.alliances = alliances
        self.winningAlliance = winningAlliance
        self.eventKey = eventKey
        self.time = time
        self.actualTime = actualTime
        self.predictedTime = predictedTime
        self.postResultTime = postResultTime
        self.scoreBreakdown = scoreBreakdown
        self.videos = videos
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["key"] = self.key
        nillableDictionary["comp_level"] = self.compLevel.rawValue
        nillableDictionary["set_number"] = self.setNumber.encodeToJSON()
        nillableDictionary["match_number"] = self.matchNumber.encodeToJSON()
        nillableDictionary["alliances"] = self.alliances?.encodeToJSON()
        nillableDictionary["winning_alliance"] = self.winningAlliance
        nillableDictionary["event_key"] = self.eventKey
        nillableDictionary["time"] = self.time?.encodeToJSON()
        nillableDictionary["actual_time"] = self.actualTime?.encodeToJSON()
        nillableDictionary["predicted_time"] = self.predictedTime?.encodeToJSON()
        nillableDictionary["post_result_time"] = self.postResultTime?.encodeToJSON()
        nillableDictionary["score_breakdown"] = self.scoreBreakdown?.encodeToJSON()
        nillableDictionary["videos"] = self.videos?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
