//
// Media.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** The &#x60;Media&#x60; object contains a reference for most any media associated with a team or event on TBA. */
public class Media: JSONEncodable {
    public enum ModelType: String { 
        case Youtube = "youtube"
        case Cdphotothread = "cdphotothread"
        case Imgur = "imgur"
        case FacebookProfile = "facebook-profile"
        case YoutubeChannel = "youtube-channel"
        case TwitterProfile = "twitter-profile"
        case GithubProfile = "github-profile"
        case InstagramProfile = "instagram-profile"
        case PeriscopeProfile = "periscope-profile"
        case Grabcad = "grabcad"
        case InstagramImage = "instagram-image"
        case ExternalLink = "external-link"
        case Avatar = "avatar"
    }
    /** TBA identifier for this media. */
    public var key: String
    /** String type of the media element. */
    public var type: ModelType
    /** The key used to identify this media on the media site. */
    public var foreignKey: String?
    /** If required, a JSON dict of additional media information. */
    public var details: AnyObject?
    /** True if the media is of high quality. */
    public var preferred: Bool?
    /** Direct URL to the media. */
    public var directUrl: String?
    /** The URL that leads to the full web page for the media, if one exists. */
    public var viewUrl: String?

    public init(key: String, type: ModelType, foreignKey: String?=nil, details: AnyObject?=nil, preferred: Bool?=nil, directUrl: String?=nil, viewUrl: String?=nil) {
        self.key = key
        self.type = type
        self.foreignKey = foreignKey
        self.details = details
        self.preferred = preferred
        self.directUrl = directUrl
        self.viewUrl = viewUrl
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["key"] = self.key
        nillableDictionary["type"] = self.type.rawValue
        nillableDictionary["foreign_key"] = self.foreignKey
        nillableDictionary["details"] = self.details?.encodeToJSON()
        nillableDictionary["preferred"] = self.preferred
        nillableDictionary["direct_url"] = self.directUrl
        nillableDictionary["view_url"] = self.viewUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
