//
// TeamEventStatusRankRanking.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class TeamEventStatusRankRanking: JSONEncodable {
    /** Number of matches played. */
    public var matchesPlayed: Int32?
    /** For some years, average qualification score. Can be null. */
    public var qualAverage: Double?
    /** Ordered list of values used to determine the rank. See the &#x60;sort_order_info&#x60; property for the name of each value. */
    public var sortOrders: [Double]?
    public var record: WLTRecord?
    /** Relative rank of this team. */
    public var rank: Int32?
    /** Number of matches the team was disqualified for. */
    public var dq: Int32?
    /** TBA team key for this rank. */
    public var teamKey: String?

    public init(matchesPlayed: Int32?=nil, qualAverage: Double?=nil, sortOrders: [Double]?=nil, record: WLTRecord?=nil, rank: Int32?=nil, dq: Int32?=nil, teamKey: String?=nil) {
        self.matchesPlayed = matchesPlayed
        self.qualAverage = qualAverage
        self.sortOrders = sortOrders
        self.record = record
        self.rank = rank
        self.dq = dq
        self.teamKey = teamKey
    }

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["matches_played"] = self.matchesPlayed?.encodeToJSON()
        nillableDictionary["qual_average"] = self.qualAverage
        nillableDictionary["sort_orders"] = self.sortOrders?.encodeToJSON()
        nillableDictionary["record"] = self.record?.encodeToJSON()
        nillableDictionary["rank"] = self.rank?.encodeToJSON()
        nillableDictionary["dq"] = self.dq?.encodeToJSON()
        nillableDictionary["team_key"] = self.teamKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
