//
// ZebraTeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ZebraTeam: Codable {

    /** The TBA team key for the Zebra MotionWorks data. */
    public var teamKey: String?
    /** A list containing doubles and nulls representing a teams X position in feet at the corresponding timestamp. A null value represents no tracking data for a given timestamp. */
    public var xs: [Double]?
    /** A list containing doubles and nulls representing a teams Y position in feet at the corresponding timestamp. A null value represents no tracking data for a given timestamp. */
    public var ys: [Double]?

    public init(teamKey: String?, xs: [Double]?, ys: [Double]?) {
        self.teamKey = teamKey
        self.xs = xs
        self.ys = ys
    }

    public enum CodingKeys: String, CodingKey { 
        case teamKey = "team_key"
        case xs
        case ys
    }


}

